name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Release
    concurrency: release

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.R_GITHUB_TOKEN }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-release.txt ]; then pip install -r requirements-release.txt; fi

    - name: Python Semantic Release
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        semantic-release publish -D commit_author="github-actions <action@github.com>"
      env:
        GH_TOKEN: ${{secrets.R_GITHUB_TOKEN}}
        PYPI_TOKEN: ${{secrets.PYPI_TOKEN}}
